AWSTemplateFormatVersion: "2010-09-09"

Description: |
  HEAT template for deploying a multi-node wordpress deployment on Rackspace Cloud
  using Cloud Servers, Cloud Load Balancers and Cloud Databases

Parameters:

  WebNodeFlavor:
    Description: Rackspace Cloud Server flavor
    Type: String
    Default: "2"
    AllowedValues:
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    ConstraintDescription: must be a valid Rackspace Cloud Server flavor.

  ServerName:
    Description: Instance name
    Type: String
    Default: Wordpress Webserver

  PublicKey:
    Description: Public SSH key that will be added to root user
    Type: String
    Default: "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAxS2c4dVUgt6X+l+Ks1qWhWBODUYW3ag1oUyIw5M4WGQlyRJCkxE26yG+schzcEBAIeDTgmycGdpEemKG9QppQmNdp20ykh5ncMzZbHE9f5+hQSotSqFCcjEUlzp4m//06M8wqVNWfJ2zs3xAelfv2iEsQg/t31aVHLF2HbPZLvmxVMj2xtrIUBXogAy9l9HjGGcYRN9eQ5gBBXPwmvP1FRFZZKx/BL+Ggk9W2G21XN53gpS6HRe6MrgD06nQMe2x5Af0+at+aSxh0bDpuNw3BkShC5OLn7K26GUjJjtStGOzMO3KkzsUUaD0qzO3+g16dSIJfxslnZlhvUjprtHKcQ== jason@carbon"

  DBName:
    Default: wordpress
    Description: The WordPress database name
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBUsername:
    Default: admin
    NoEcho: True
    Description: The WordPress database admin account username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    Default: admin
    NoEcho: true
    Description: The WordPress database admin account password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern : "[a-zA-Z0-9]*"
    ConstraintDescription : must contain only alphanumeric characters.

  DBFlavor:
    Description : Database instance size
    Type: String
    Default: 1GB Instance

  VolumeSize: 
    Description : "The database volume size (in GB)"
    Type: Number
    MinValue: 1
    MaxValue: 1024
    Default: 30

  InstanceName: 
    Description: The database instance name
    Type: String
    Default: WP_Cloud_DB

Resources:

  WebNode1: 
    Type: "Rackspace::Cloud::Server"
    Metadata : 
      "AWS::CloudFormation::Init": 
        config: 
          packages: 
            yum: 
              mysql: []
              httpd: []
              wordpress: []
          services: 
            systemd: 
              httpd:
                enabled: True
                ensureRunning: true 
    Properties:
      Flavor:
        Ref: WebNodeFlavor
      ImageName: "Fedora 17 (Beefy Miracle)"
      ServerName:
        "Fn::Replace":
        - { "%SERVER_NAME%": { "Ref": "ServerName" } }
        - "%SERVER_NAME%-1"
      PublicKey:
        Ref: PublicKey
      UserData: { "Fn::Base64" : { "Fn::Join" : ["", [
                    "#!/bin/bash -v\n",
                    "/usr/bin/cfn-init\n",
                    "# Setup MySQL root password and create a user\n",
                    "mysqladmin -u root password '", { "Ref" : "DBRootPassword" }, "'\n",
                    "cat << EOF | mysql -u root --password='", { "Ref" : "DBRootPassword" }, "'\n",
                    "CREATE DATABASE ", { "Ref" : "DBName" }, ";\n",
                    "GRANT ALL PRIVILEGES ON ", { "Ref" : "DBName" }, ".* TO \"", { "Ref" : "DBUsername" }, "\"@\"localhost\"\n",
                    "IDENTIFIED BY \"", { "Ref" : "DBPassword" }, "\";\n",
                    "FLUSH PRIVILEGES;\n",
                    "EXIT\n",
                    "EOF\n",
                    "sed -i \"/Deny from All/d\" /etc/httpd/conf.d/wordpress.conf\n",
                    "sed -i \"s/Require local/Require all granted/\" /etc/httpd/conf.d/wordpress.conf\n",
                    "sed --in-place --e s/database_name_here/", { "Ref" : "DBName" }, "/ --e s/username_here/", { "Ref" : "DBUsername" }, "/ --e s/password_here/", { "Ref" : "DBPassword" }, "/ /usr/share/wordpress/wp-config.php\n",
                    "systemctl restart httpd.service\n",
                    "iptables -I INPUT -p tcp --dport 80 -j ACCEPT\n",
                    "iptables-save > /etc/sysconfig/iptables\n"
              ]]}}

  WebNode2: 
    Type: "Rackspace::Cloud::Server"
    Metadata : 
      "AWS::CloudFormation::Init": 
        config: 
          packages: 
            yum: 
              mysql: []
              httpd: []
              wordpress: []
          services: 
            systemd: 
              httpd:
                enabled: True
                ensureRunning: true 
    Properties:
      Flavor:
        Ref: WebNodeFlavor
      ImageName: "Fedora 17 (Beefy Miracle)"
      ServerName:
        "Fn::Replace":
        - { "%SERVER_NAME%": { "Ref": "ServerName" } }
        - "%SERVER_NAME%-2"
      PublicKey:
        Ref: PublicKey
      UserData: { "Fn::Base64" : { "Fn::Join" : ["", [
                  "#!/bin/bash -v\n",
                  "/usr/bin/cfn-init\n",
                  "sed -i \"/Deny from All/d\" /etc/httpd/conf.d/wordpress.conf\n",
                  "sed -i \"s/Require local/Require all granted/\" /etc/httpd/conf.d/wordpress.conf\n",
                  "sed --in-place --e s/localhost/",
                  { "Fn::GetAtt": [ "MySqlCloudDatabaseServer", "hostname" ] },
                  "/ --e s/database_name_here/",
                  { "Ref" : "DBName" },
                  "/ --e s/username_here/",
                  { "Ref" : "DBUsername" },
                  "/ --e s/password_here/",
                  { "Ref" : "DBPassword" },
                  "/ /usr/share/wordpress/wp-config.php\n",
                  "systemctl restart httpd.service\n"
        ]]}}

  LoadBalancer:
    Type: "Rackspace::Cloud::LoadBalancer"
    Properties:
name: "Wordpress Loadbalancer"
      nodes:
      - ref: { "Ref":  "WebNode1"}
        port: 80
        condition: ENABLED
      - ref: { "Ref":  "WebNode2"}
        port: 80
        condition: ENABLED
      protocol: HTTP
      halfClosed: False
      algorithm: LEAST_CONNECTIONS
      connectionLogging: True
      connectionThrottle:
        maxConnections: 50
        minConnections: 50
        maxConnectionRate: 50
        rateInterval: 50
      port: 80
      timeout: 120
      sessionPersistence: HTTP_COOKIE
      virtualIps:
      - type: PUBLIC
        ipVersion: IPV4
      healthMonitor:
        type: HTTP
        delay: 10
        timeout: 10
        attemptsBeforeDeactivation: 3
        path: "/"
        statusRegex: "."
        bodyRegex: "."
        hostHeader: "example.com"
      contentCaching: ENABLED
      errorPage: You were a bad person, causing errors and such.
      accessList:
      - address: "173.194.77.103"
        type: DENY

  MySqlCloudDatabaseServer:
    Type: "Rackspace::Cloud::DBInstance"
    Properties:
      InstanceName:
        Ref: InstanceName
      FlavorRef:
        Ref: DBFlavor
      VolumeSize:
        Ref: VolumeSize
      Users:
      - Name: { "Ref": "DBUsername" }
        Password: { "Ref": "DBPassword" }
        Databases:
        - { "Ref": "DBName" }
      Databases:
      - Name: { "Ref": "DBName" }

Outputs:

  WebsiteURL:
    Value: { "Fn::Join" : ["", ["http://", { "Fn::GetAtt" : [ "LoadBalancer", "PublicIp" ]}, "/wordpress"]] }
    Description: URL for Wordpress wiki

