AWSTemplateFormatVersion: "2010-09-09"

Description: |
  A template implementation of a resource that provides a Wordpress
  blog server

Parameters:

  Flavor:
    Description: Rackspace Cloud Server flavor
    Type: String
    Default: "2"
    AllowedValues:
    - "2"
    - "3"
    - "4"
    - "5"
    - "6"
    - "7"
    - "8"
    ConstraintDescription: must be a valid Rackspace Cloud Server flavor.

  ServerName:
    Description: Instance name
    Type: String
    Default: Wordpress Webserver
 
  DBHost:
    Description: The database hostname
    Type: String
    Default: localhost

  DBName:
    Default: wordpress
    Description: The WordPress database name
    Type: String
    MinLength: 1
    MaxLength: 64
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBUsername:
    Default: admin
    NoEcho: "true"
    Description: The WordPress database admin account username
    Type: String
    MinLength: 1
    MaxLength: 16
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters.

  DBPassword:
    Default: admin
    NoEcho: "true"
    Description: The WordPress database admin account password
    Type: String
    MinLength: 1
    MaxLength: 41
    AllowedPattern : "[a-zA-Z0-9]*"
    ConstraintDescription : must contain only alphanumeric characters.

Resources:

  Wordpress: 
    Type: "Rackspace::Cloud::Server"
    Metadata : 
      "AWS::CloudFormation::Init": 
        config: 
          packages: 
            yum: 
              mysql: []
              httpd: []
              wordpress: []
          services: 
            systemd: 
              httpd:
                enabled: True
                ensureRunning: true 
    Properties:
      Flavor:
        Ref: Flavor
      ImageName: "Fedora 17 (Beefy Miracle)"
      ServerName: { "Ref": "ServerName" }
      UserData: { "Fn::Base64" : { "Fn::Join" : ["", [
                  "#!/bin/bash -v\n",
                  "/usr/bin/cfn-init\n",
                  "sed -i \"/Deny from All/d\" /etc/httpd/conf.d/wordpress.conf\n",
                  "sed -i \"s/Require local/Require all granted/\" /etc/httpd/conf.d/wordpress.conf\n",
                  "sed --in-place --e s/localhost/",
                  { "Ref": "DBHost" },
                  "/ --e s/database_name_here/",
                  { "Ref" : "DBName" },
                  "/ --e s/username_here/",
                  { "Ref" : "DBUsername" },
                  "/ --e s/password_here/",
                  { "Ref" : "DBPassword" },
                  "/ /usr/share/wordpress/wp-config.php\n",
                  "systemctl restart httpd.service\n",
                  "iptables -I INPUT -p tcp --dport 80 -j ACCEPT\n",
                  "iptables-save > /etc/sysconfig/iptables\n"
              ]]}}

Outputs:
  
  PublicIp:
    Value: { "Fn::GetAtt" : [ "Wordpress", "PublicIp" ] }
    Description: The public ip address of the server

  PrivateIp:
    Value: { "Fn::GetAtt" : [ "Wordpress", "PrivateIp" ] }
    Description: The private ip address of the server

  WebsiteURL:
    Value: { "Fn::Join" : ["", ["http://", { "Fn::GetAtt" : [ "Wordpress", "PublicIp" ]}, "/wordpress"]] }
    Description: URL for Wordpress wiki

